import { icons } from "../../assets/icons";

export const farmingId = "catalogo";
export const buildingId = "building";

export const farmingList = {
	id: farmingId,
	index: 1,
	subMenus: [
		{
			id: "submenu-6",
			title: "Tractor",
			cards: [
				{
					cardTitle: "3036E DT",
					description: "",
					preview: (new Image().src = icons.farmer_3036E),
					id: "card-1",
					machine: "3036e",
					info: [
						"Potencia al Motor: 36 HP",
						"Potencia a la Toma de Fuerza: 28 HP",
						"Transmisión: 8A / 8R SyncReverser™",
						"Cantidad de Cilindros: 3",
						"Capacidad Máxima de Levante: 910 kg (a las esferas)",
					],
				},
				{
					cardTitle: "5076EN",
					description: "",
					preview: (new Image().src = icons.farmer_5076EN),
					id: "card-2",
					machine: "5076EN",
					info: [
						"Potencia al Motor: 75 HP",
						"Potencia a la Toma de Fuerza: 62.7 HP",
						"Transmisión: 12A / 12R PowrReverser™",
						"Cantidad de Cilindros: 4",
						"Capacidad Máxima de Levante: 1,972.3 kgf (a las esferas)",
					],
				},
				{
					cardTitle: "5076E DT",
					description: "",
					preview: (new Image().src = icons.farmer_50766DT),
					id: "card-3",
					machine: "5076E",
					info: [
						"Potencia al Motor: 77 HP",
						"Potencia a la Toma de Fuerza: 70.3 HP",
						"Transmisión: 9A / 3R Sincronizada",
						"Cantidad de Cilindros: 4",
						"Capacidad Máxima de Levante: 1,972.3 kgf (a las esferas)",
					],
				},
				{
					cardTitle: "5415 DT",
					description: "",
					preview: (new Image().src = icons.farmer_5415_DT),
					id: "card-4",
					machine: "5415",
					info: [
						"Potencia al Motor: 77 HP",
						"Potencia a la Toma de Fuerza: 67 HP",
						"Transmisión: 9A / 3R Sincronizada",
						"Cantidad de Cilindros: 4",
						"Capacidad Máxima de Levante: 2003.85 kgf (a las esferas)",
					],
				},
				{
					cardTitle: "5082E DT CAB",
					description: "",
					preview: (new Image().src = icons.farmer_5082E_DT_CAB),
					id: "card-5",
					machine: "5082E",
					info: [
						"Potencia al Motor: 81 HP",
						"Potencia a la Toma de Fuerza: 70.2 HP",
						"Transmisión: 9A / 3R Sincronizada. Opcional 12A / 12R PowrReverser™",
						"Cantidad de Cilindros: 4",
						"Capacidad Máxima de Levante: 1,972.3 kgf (a las esferas)",
					],
				},
				{
					cardTitle: "5090E TS",
					description: "",
					preview: (new Image().src = icons.farmer_5090E_DT_CAB),
					id: "card-6",
					machine: "5090E",
					info: [
						"Potencia al Motor: 89 HP",
						"Potencia a la Toma de Fuerza: 83.3 HP",
						"Transmisión: 9A/3R Sincronizada. Opcional 12A/12R PowrReverser™",
						"Cantidad de Cilindros: 4",
						"Capacidad Máxima de Levante: 1,972.3 kgf (a las esferas)",
					],
				},
				{
					cardTitle: "5090E DT CAB",
					description: "",
					preview: (new Image().src = icons.farmer_5090E_DT_CAB),
					id: "card-7",
					machine: "5090E_2",
					info: [
						"Potencia al Motor: 89 HP",
						"Potencia a la Toma de Fuerza: 83.3 HP",
						"Transmisión: 9A/3R Sincronizada. Opcional 12A/12R PowrReverser™",
						"Cantidad de Cilindros: 4",
						"Capacidad Máxima de Levante: 1,972.3 kgf (a las esferas)",
					],
				},
				{
					cardTitle: "5090EH",
					description: "",
					preview: (new Image().src = icons.farmer_5090E_DT_CAB),
					id: "card-8",
					machine: "5090EH",
					info: [
						"Potencia al Motor: 89 HP",
						"Potencia a la Toma de Fuerza: 83.3 HP",
						"Transmisión: 9A/3R Sincronizada. Opcional 12A/12R PowrReverser™",
						"Cantidad de Cilindros: 4",
						"Capacidad Máxima de Levante: 1,972.3 kgf (a las esferas)",
					],
				},
				{
					cardTitle: "6105EH CAB",
					description: "",
					preview: (new Image().src = icons.farmer_6105EH_cab),
					id: "card-9",
					machine: "6105EH",
					info: [
						"Potencia al Motor: 106 HP",
						"Transmisión: 12A/12R PowrReverser™ con creeper",
						"Cantidad de Cilindros: 4",
						"Capacidad Máxima de Levante: 3,420 kg",
					],
				},
				{
					cardTitle: "6105J DT",
					description: "",
					preview: (new Image().src = icons.farmer_6105J_DT_CAB),
					id: "card-10",
					machine: "6105J",
					info: [
						"Potencia al Motor: 105 HP",
						"Potencia a la Toma de Fuerza: 90 HP",
						"Transmisión: 12A/4R SyncroPlus™ para OOS y 16A/16R PowrQuad™ para CAB",
						"Cantidad de Cilindros: 4",
						"Capacidad Máxima de Levante: 3,117 kg",
					],
				},
				{
					cardTitle: "6105J H",
					description: "",
					preview: (new Image().src = icons.farmer_6105J_H),
					id: "card-11",
					machine: "6105J_2",
					info: [
						"Potencia al Motor: 105 HP",
						"Potencia a la Toma de Fuerza: 90 HP",
						"Transmisión: 12A/4R SyncroPlus™ para OOS y 16A/16R PowrQuad™ para CAB",
						"Cantidad de Cilindros: 4",
						"Capacidad Máxima de Levante: 3,117 kg",
					],
				},
				{
					cardTitle: "6120EH",
					description: "",
					preview: (new Image().src = icons.farmer_6120EH_CAB),
					id: "card-12",
					machine: "6120EH",
					info: [
						"Potencia al Motor: 123 HP",
						"Potencia a la Toma de Fuerza: 108 HP",
						"Transmisión: 12A/12R PowrReverser™ con creeper",
						"Cantidad de Cilindros: 4",
						"Capacidad Máxima de Levante: 3,420 kg",
					],
				},
				{
					cardTitle: "6125E DT CAB",
					description: "",
					preview: (new Image().src = icons.farmer_6125E_DT_CAB),
					id: "card-13",
					machine: "6125E",
					info: [
						"Potencia al Motor: 123 HP",
						"Potencia a la Toma de Fuerza: 108 HP",
						"Transmisión: 12A/12R PowrReverser™",
						"Cantidad de Cilindros: 4",
						"Capacidad Máxima de Levante: 3,420 kg",
					],
				},
				{
					cardTitle: "6403 DT CAB",
					description: "",
					preview: (new Image().src = icons.farmer_6403_DT_CAB),
					id: "card-14",
					machine: "6403",
					info: [
						"Potencia al Motor: 109 HP",
						"Potencia a la Toma de Fuerza: 96 HP",
						"Transmisión: 12A / 4R SyncShuttle™",
						"Cantidad de Cilindros: 4",
						"Capacidad Máxima de Levante: 3,420 kg",
					],
				},
				{
					cardTitle: "6603 DT CAB",
					description: "",
					preview: (new Image().src = icons.farmer_6603_DT_CAB),
					id: "card-15",
					machine: "6603",
					info: [
						"Potencia al Motor: 124 HP",
						"Potencia a la Toma de Fuerza: 103 HP",
						"Transmisión: 12A / 4R SyncShuttle™",
						"Cantidad de Cilindros: 6",
						"Capacidad Máxima de Levante: 3,420 kg",
					],
				},
				{
					cardTitle: "6155J DT CAB",
					description: "",
					preview: (new Image().src = icons.farmer_6155J_DT),
					id: "card-16",
					machine: "6155J",
					info: [
						"Potencia al Motor: 155 HP",
						"Potencia a la Toma de Fuerza: 135 HP",
						"Transmisión: 16A / 16R PowrQuad™",
						"Cantidad de Cilindros: 6",
						"Capacidad Máxima de Levante: 3,805 kg",
					],
				},
				{
					cardTitle: "7230J",
					description: "",
					preview: (new Image().src = icons.farmer_7230J),
					id: "card-17",
					machine: "7230J",
					info: [
						"Potencia al Motor: 227 HP",
						"Potencia a la Toma de Fuerza: ", // La información para la potencia a la toma de fuerza está incompleta
						"Transmisión: 16A / 16R AutoQuad™",
						"Cantidad de Cilindros: 6",
						"Capacidad Máxima de Levante: 6,350 kg",
					],
				},
				{
					cardTitle: "8R 280",
					description: "",
					preview: (new Image().src = icons.farmer_8R_280),
					id: "card-18",
					machine: "280",
					info: [
						"Potencia al Motor: 280 HP",
						"Potencia a la Toma de Fuerza: 228 HP",
						"Transmisión: 16A/5R PowerShift",
						"Cantidad de Cilindros: 6",
						"Capacidad Máxima de Levante: 6,894 kg",
					],
				},
			],
		},
		{
			id: "submenu-7",
			title: "Equipos cortacesped",
			cards: [
				{
					cardTitle: "530M",
					description: "",
					preview: (new Image().src = icons.farmer_Z530M),
					id: "card-1",
					machine: "Z530m",
					info: [
						"Motor: Gasolina",
						"Transmisión: Hidrostática",
						"Cantidad de Cilindros: 2 V",
						"Ancho de Plataforma de Corte: 158,7",
						"Capacidad de Combustible: 17 litros",
					],
				},
				{
					cardTitle: "S140",
					description: "",
					preview: (new Image().src = icons.farmer_S140),
					id: "card-2",
					machine: "S140",
					info: [
						"Potencia al Motor: 22 HP",
						"Radio de Giro: 45.7 cm",
						"Transmisión: Hidrostática",
						"Cantidad de Cilindros: 2 V",
						"Velocidad Máxima de Avance: 8.9 km/h",
						"Velocidad Máxima de Retroceso: 5.2 km/h",
					],
				},
			],
		},
		{
			id: "submenu-8",
			title: "Dron Agras",
			cards: [
				{
					cardTitle: "T40",
					description: "",
					preview: (new Image().src = icons.farmer_Agras_T40),
					id: "card-1",
					machine: "Agras740",
					info: [
						"Potencia del Motor: 4000 W/rotor",
						"Capacidad de Carga: 40 kg",
						"Altitud Máxima de Vuelo: 100 m",
						"Distancia Máxima de Vuelo: 2 km",
						"Velocidad Máxima de Vuelo: 10 m/s",
					],
				},
			],
		},
	],
};
export const buildingList = {
	id: buildingId,
	index: 2,
	subMenus: [
		{
			id: "submenu-1",
			title: "Cargador de Ruedas",
			cards: [
				{
					cardTitle: "644G",
					description: "",
					preview: (new Image().src = icons.building_644G),
					id: "card-1",
					machine: "644",
					info: [
						"Potencia Neta: 185 kW (248 hp) a 1800 rpm",
						"ÏPeso en Orden de Trabajo: 17 095–17 314 kg (37 688–38 170 lb.)",
						"Capacidad del Cucharón: 3,10–3,25 m³ (4,00–4,25 yd³)",
					],
				},
			],
		},
		{
			id: "submenu-2",
			title: "Retroexcavadora",
			cards: [
				{
					cardTitle: "320P",
					description: "",
					preview: (new Image().src = icons.building_320P),
					id: "card-1",
					machine: "320P",
					info: [
						"Potencia Máxima Neta: 72 Kw (97 HP) a 2000 rpm",
						"Transmisión: PowerShift de 5 velocidades",
						"Capacidad del Cucharón: 0,86 m³ ",
					],
				},
				{
					cardTitle: "310L 4x4",
					description: "",
					preview: (new Image().src = icons.building_310L),
					id: "card-2",
					machine: "310L",
					info: [
						"Potencia Máxima Neta: 68 Kw (91 HP) a 1800 rpm",
						"Transmisión: PowerShift de 4 velocidades",
						"Capacidad del Cucharón: 0,96 m³ (1,25 yd3)",
					],
				},
			],
		},
		{
			id: "submenu-3",
			title: "Motoniveladora",
			cards: [
				{
					cardTitle: "620G",
					description: "",
					preview: (new Image().src = icons.building_620G),
					id: "card-1",
					machine: "620G",
					info: [
						"Potencia neta del motor: 108–149 kW (145–200 CV)",
						"Par motor neto máximo: 915 Nm (675 lb.-ft.)",
						"Fuerza de Arrastre de la Hoja: 14 091 kg (31,066 lb.)",
						"Aumento neto del par motor: 46%",
					],
				},
				{
					cardTitle: "670G",
					description: "",
					preview: (new Image().src = icons.building_670G),
					id: "card-2",
					machine: "670G",
					info: [
						"Potencia neta del motor: 118–157 kW (158–210 CV)",
						"Par motor neto máximo: 1124 Nm (829 lb.-ft.)",
						"Fuerza de Arrastre de la Hoja: 12 800 kg (28,220 lb.)",
						"Aumento neto del par motor: 77%",
					],
				},
			],
		},
		{
			id: "submenu-4",
			title: "Excavadora",
			cards: [
				{
					cardTitle: "200G",
					description: "",
					preview: (new Image().src = icons.building_200G),
					id: "card-1",
					machine: "200G",
					info: [
						"Potencia neta del motor: 95 kW (130 CV) a 1900 rpm",
						"Profundidad máx. de excavación: 7,07 m (23 ft 2 in)",
						"Peso operativo: 20 205 kg (44 504 lb)",
					],
				},
				{
					cardTitle: "210G LC",
					description: "",
					preview: (new Image().src = icons.building_210G_LC),
					id: "card-2",
					machine: "210GLC",
					info: [
						"Potencia neta del motor: 119 kW (159 CV) a 1900 rpm",
						"Profundidad máx. de excavación: 6,68 m (21 ft 11 in)",
						"Peso operativo: 21 914 kg (48 312 lb.)",
					],
				},
			],
		},
		{
			id: "submenu-5",
			title: "Miniexcavadora",
			cards: [
				{
					cardTitle: "35G",
					description: "",
					preview: (new Image().src = icons.building_35G),
					id: "card-1",
					machine: "35G",
					info: ["Velocidad Máxima de Recorrido: Baja 2,8 km/h. Alta 4,3 km/h", "Profundidad de Excavación Máxima: 3,06 m"],
				},
			],
		},
		{
			id: "submenu-6",
			title: "Minicargador",
			cards: [
				{
					cardTitle: "318G",
					description: "",
					preview: (new Image().src = icons.building_318G),
					id: "card-2",
					machine: "318G",
					info: [
						"Capacidad de operación nominal: 883 kg (1945 lb.)",
						"Potencia Bruta: 44 kW (60 CV) a 2600 rpm",
						"Potencia neta: 42 kW (56 CV) a 2.600 rpm",
						"Peso operativo: 2970 kg (6542 lb.)",
					],
				},
			],
		},
	],
};
